import { gql } from "@apollo/client";

export const GET_DATA_QUERY = gql`
query{
  persona{
  	data{
      attributes{
        title
        description
        shipwreck_image{
          data{
              attributes{
                url
                alternativeText
                height
                width
              }
          }
        }
        captain_image{
                    data{
              attributes{
                url
                alternativeText
                height
                width
              }
          }
        }
        tattooed_image{
                    data{
              attributes{
                url
                alternativeText
                height
                width
              }
          }
        }
        personas{
          id
          title
          description
        }
      }
    }
  }
  ourValue{
    data{
      attributes{
        title
        values{
          title
          description
          image{
            data{
              attributes{
                url
                alternativeText
                height
                width
              }
            }
          }
        }
      }
    }
  }
  rule{
    data{
      attributes{
        title
        description
        rules{
          id
          description
          image{
            data{
              attributes{
                url
                alternativeText
                width
                height
              }              
            }
          }
        }
      }
    }
  }
  layout{
    data{
      attributes{
        title
        description
        layout_image{
          data{
            attributes{
              url
              alternativeText
              width
              height
            }
          }
        }
                layout_image_magnified{
          data{
            attributes{
              url
              alternativeText
              width
              height
            }
          }
        }
      }
    }
  }
  illustration{
    data{
      attributes{
        title
        description
        download{
          data{
            attributes{
              url
            }
          }
        }
        illustrations{
          label
          id
          image{
            data{
              attributes{
                url
                alternativeText
                width
                height
              }
            }
          }
        }
      }
    }
  }
  texture{
    data{
      attributes{
        title
        description
        texture_images{
          data{
            id
            attributes{              
              width
              height
              url
            }
          }
        }
        download{
          data{
            attributes{
              url
            }
          }
        }
      }
    }
  }
  photography{
    data{
      attributes{
        title
        description
        download{
          data{
            attributes{
              url
            }
          }
        }
        photography{
          label
          id
          width
          height
          image{
            data{
              attributes{
                url
                width
                height
                alternativeText
              }
            }
          }
        }
      }
    }
  }
  color{
    data{
      attributes{
        title
        description
        primary_colors{
          id
          background_color
          title
          title_color
          code_color
          hexcode
          rgb
          rgba
        }
        secondary_title
        secondary_description
        secondary_colors{
          id
          background_color
          code_color
          hexcode
          rgb
        }
      }
    }
  }
  typography{
    data{
      attributes{
        title
        description
        download{
          data{
            attributes{
              url
            }
          }
        }
        typography{
          id
          font_family
          description
          title
        }
      }
    }
  }
  logo{
    data{
      attributes{
        title
        primary_title
        primary_description
        primary_salty
        primary_logos{
          id
          background_color
          image{
            data{
              attributes{
                url
                alternativeText
                width
                height
              }
            }
          }
        }
        simplified_title
        simplified_description
        simplified_logos{
          background_color
          image{
            data{
              attributes{
                url
                alternativeText
                width
                height
              }
            }
          }
        }
        simplified_salty
        flag_title
        flag_description
        flag_logos{
          background_color
                    image{
            data{
              attributes{
                url
                alternativeText
                width
                height
              }
            }
          }
        }
        flag_salty
        download{
          data{
            attributes{
              url
            }
          }
        }
      }
    }
  }
  grit{
    data{
      attributes{
        title
        description
        salty
        fish_image{
                    data{
            attributes{
              alternativeText
              width
              height
              url
            }
          }
        }
        fisherman_image{
                    data{
            attributes{
              alternativeText
              width
              height
              url
            }
          }
        }
        cliff_image{
                    data{
            attributes{
              alternativeText
              width
              height
              url
            }
          }
        }
      }
    }
  }
  boilerplate{
    data{
      attributes{
        about{
          description
          title
          id
        }
      }
    }
  }
  positioning{
    data{
    attributes{
      title
      description
      bullets
      positioning{
        id
        title
        description
      }
    }
    }
  }
  hero{
    data{
      attributes{
        title
        description
        salty
        top_right_image{
          data{
            attributes{
              alternativeText
              width
              height
              url
            }
          }
        }
        bottom_left_image{
          data{
            attributes{
              alternativeText
              width
              height
              url
            }
          }
        }
        bottom_middle_image{
                    data{
            attributes{
              alternativeText
              width
              height
              url
            }
          }
        }
        bottom_right_image{
                    data{
            attributes{
              alternativeText
              width
              height
              url
            }
          }
        }
        
      }
    }
  }
  voice{
    data{
      attributes{
        title
        tone
        description
        portrait_image{
            data{
            attributes{
              alternativeText
              width
              height
              url
            }
          }
        }
        background_image{
						data{
            attributes{
              alternativeText
              width
              height
              url
            }
          }
        }
        boat_image{
          data{
            attributes{
              alternativeText
              width
              height
              url
            }
          }
        }
        dog_image{
          data{
            attributes{
              alternativeText
              width
              height
              url
            }
          }
        }
      }
    }
  }
}
`;
